# Generated by Django 3.2.7 on 2023-02-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='for_me/photos/', verbose_name='Фотки')),
                ('name', models.CharField(max_length=127, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=127, verbose_name='Автор')),
                ('photo', models.ImageField(upload_to='for_me/photo/', verbose_name='Фотка')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='for_me/photo/', verbose_name='Фотка')),
                ('name', models.CharField(max_length=127, verbose_name='ФИО')),
                ('gender', models.CharField(max_length=127, verbose_name='Пол')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='for_me/logos/', verbose_name='Логотип сайта')),
                ('whatsapp', models.URLField(verbose_name='Вотсапп')),
                ('twitter', models.URLField(verbose_name='Твиттер')),
                ('facebook', models.URLField(verbose_name='Фейсбук')),
                ('name', models.CharField(max_length=127, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('admissiontouniversity', models.CharField(max_length=127, verbose_name='Поступление')),
                ('staff', models.PositiveIntegerField(verbose_name='Персонал')),
                ('students', models.PositiveIntegerField(verbose_name='Студенты')),
                ('successworkyear', models.CharField(max_length=127, verbose_name='Рабочий год')),
                ('mail', models.URLField(verbose_name='Почта')),
                ('address', models.CharField(max_length=127, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=127, verbose_name='Позиция')),
                ('name', models.CharField(max_length=127, verbose_name=' Имя')),
                ('photo', models.ImageField(upload_to='for_me/photo/', verbose_name='Фото')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='mainapp.school')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
